[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 10
restartPolicyType = "on_failure"
numReplicas = 1

[deploy.envs]
NODE_ENV = "production" 