[build]
builder = "nixpacks"
buildCommand = "cd starter && NODE_ENV=production npm install && npm run build"

[deploy]
startCommand = "cd starter && npm run preview"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[deploy.envs]
NODE_ENV = "production" 