[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 10
restartPolicyType = "on_failure"
numReplicas = 1

[deploy.envs]
NODE_ENV = "production"
PORT = "3000" 