name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install dependencies in the root folder
      - run: npm install concurrently --save-dev
      
      # Install dependencies in the 'starter' folder (frontend)
      - run: |
          cd starter
          npm install
      
      # Install dependencies in the 'twilio-sms-server' folder (backend)
      - run: |
          cd twilio-sms-server
          npm install
      
      # Start the services
      - run: npm start
      
      # Deploy to Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BOOT_WATCHER }}
          channelId: live
          projectId: boot-watcher
