name: Deploy App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Step 3: Install and run SMS Server (Twilio SMS Server)
      - name: Install Server Dependencies
        working-directory: twilio-sms-server
        run: |
          npm install

      - name: Start Server
        working-directory: twilio-sms-server
        run: |
          npm start

      # Step 4: Install and build Starter (Client)
      - name: Install and build Client
        working-directory: starter
        run: |
          npm install
          npm run build
